### ISSUE TITLE
Review for changes in Gluon 2016.1 

### ISSUE THREAD

**Issue by Byggvir** [Byggvir/ff-rhb#2]
The site.conf parameters are changed and new parameters will be introduced with Gluon 2015.2 / 2016.1.

This site configuration reflects some changed parameters. I am still not sure if I addressed all changes yet.

**Comment by cmarxmeier** [comment]
you didn't.
site.conf:
meshing protocol was switchted from ibss0 to mesh0 a while ago -  your nodes will propably not mesh with the rsk firmware ones 
see: https://github.com/Freifunk-Rhein-Sieg/sites-rsk/blob/rheinbach-v2016.2/site.conf
https://github.com/Freifunk-Rhein-Sieg/freifunk-packages - additional packages for rsk 4 meshcheck in bigger installations etc.
switching to gluon 2016.2.x tree is suggested.

and second key for autoupdate is published by stefan from ff-tdf for rsk-firmware when testing was successful and rollouts are going to happen - not directly after compiling new images ;)

**Comment by Byggvir** [comment]
I'm on 2016.2.x for Rheinbach nodes and don't uses Stefans images. Most nodes mesh on mesh0 / mesh1. ibss is diesabled in the site config.

Will test an rsk node this weekend.

**Comment by cmarxmeier** [comment]
in progress to change to tunneldigger (l2tp) - Siegburg and Lohmar evaluate - see http://crm.rettesichwerkann.de/?q=node/27
stefans firmware will remain standard config with fastd using wuppertal supernodes
meshing params for mesh0 changed also not to cause trouble and looptraffic

**Comment by cmarxmeier** [comment]
see https://github.com/Freifunk-Siegburg/ffsu-site for l2tp changes in site.mk and .conf

tunneldigger packages from ffrl repo
